version: '3'
services:
  mongodb:
    image: mongo:3.6.18
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  app:
    image: rlkamradt/newsreader
    environment:
      NEWSAPI_KEY: ${NEWSAPI_KEY}
      MONGO_USER: admin
      MONGO_PASS: admin
    depends_on:
      - "mongodb"
